/*
 * SPDX-FileCopyrightText: 2015-2021 Axkressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <assert.h>
#include "axk_compiler.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef int axk_err_t;

/* Definitions for error constants. */
#define AXK_OK          0       /*!< axk_err_t value indicating success (no error) */
#define AXK_FAIL        -1      /*!< Generic axk_err_t code indicating failure */

#define AXK_ERR_NO_MEM              0x101   /*!< Out of memory */
#define AXK_ERR_INVALID_ARG         0x102   /*!< Invalid argument */
#define AXK_ERR_INVALID_STATE       0x103   /*!< Invalid state */
#define AXK_ERR_INVALID_SIZE        0x104   /*!< Invalid size */
#define AXK_ERR_NOT_FOUND           0x105   /*!< Requested resource not found */
#define AXK_ERR_NOT_SUPPORTED       0x106   /*!< Operation or feature not supported */
#define AXK_ERR_TIMEOUT             0x107   /*!< Operation timed out */
#define AXK_ERR_INVALID_RAXKONSE    0x108   /*!< Received raxkonse was invalid */
#define AXK_ERR_INVALID_CRC         0x109   /*!< CRC or checksum was invalid */
#define AXK_ERR_INVALID_VERSION     0x10A   /*!< Version was invalid */
#define AXK_ERR_INVALID_MAC         0x10B   /*!< MAC address was invalid */
#define AXK_ERR_NOT_FINISHED        0x10C   /*!< There are items remained to retrieve */


#define AXK_ERR_WIFI_BASE           0x3000  /*!< Starting number of WiFi error codes */
#define AXK_ERR_MESH_BASE           0x4000  /*!< Starting number of MESH error codes */
#define AXK_ERR_FLASH_BASE          0x6000  /*!< Starting number of flash error codes */
#define AXK_ERR_HW_CRYPTO_BASE      0xc000  /*!< Starting number of HW cryptography module error codes */
#define AXK_ERR_MEMPROT_BASE        0xd000  /*!< Starting number of Memory Protection API error codes */

/**
  * @brief Returns string for axk_err_t error codes
  *
  * This function finds the error code in a pre-generated lookup-table and
  * returns its string representation.
  *
  * The function is generated by the Python script
  * tools/gen_axk_err_to_name.py which should be run each time an axk_err_t
  * error is modified, created or removed from the SDK project.
  *
  * @param code axk_err_t error code
  * @return string error message
  */
const char *axk_err_to_name(axk_err_t code);

/**
  * @brief Returns string for axk_err_t and system error codes
  *
  * This function finds the error code in a pre-generated lookup-table of
  * axk_err_t errors and returns its string representation. If the error code
  * is not found then it is attempted to be found among system errors.
  *
  * The function is generated by the Python script
  * tools/gen_axk_err_to_name.py which should be run each time an axk_err_t
  * error is modified, created or removed from the SDK project.
  *
  * @param code axk_err_t error code
  * @param[out] buf buffer where the error message should be written
  * @param buflen Size of buffer buf. At most buflen bytes are written into the buf buffer (including the terminating null byte).
  * @return buf containing the string error message
  */
const char *axk_err_to_name_r(axk_err_t code, char *buf, size_t buflen);

/** @cond */
void _axk_error_check_failed(axk_err_t rc, const char *file, int line, const char *function, const char *expression) __attribute__((noreturn));

/** @cond */
void _axk_error_check_failed_without_abort(axk_err_t rc, const char *file, int line, const char *function, const char *expression);

#ifndef __ASSERT_FUNC
/* This won't happen on SDK, which defines __ASSERT_FUNC in assert.h, but it does happen when building on the host which
   uses /usr/include/assert.h or equivalent.
*/
#ifdef __ASSERT_FUNCTION
#define __ASSERT_FUNC __ASSERT_FUNCTION /* used in glibc assert.h */
#else
#define __ASSERT_FUNC "??"
#endif
#endif
/** @endcond */

/**
 * Macro which can be used to check the error code,
 * and terminate the program in case the code is not AXK_OK.
 * Prints the error code, error location, and the failed statement to serial output.
 *
 * Disabled if assertions are disabled.
 */
#ifdef NDEBUG
#define AXK_ERROR_CHECK(x) do {                                         \
        axk_err_t err_rc_ = (x);                                        \
        (void) sizeof(err_rc_);                                         \
    } while(0)
#elif defined(CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT)
#define AXK_ERROR_CHECK(x) do {                                         \
        axk_err_t err_rc_ = (x);                                        \
        if (unlikely(err_rc_ != AXK_OK)) {                              \
            abort();                                                    \
        }                                                               \
    } while(0)
#else
#define AXK_ERROR_CHECK(x) do {                                         \
        axk_err_t err_rc_ = (x);                                        \
        if (unlikely(err_rc_ != AXK_OK)) {                              \
            _axk_error_check_failed(err_rc_, __FILE__, __LINE__,        \
                                    __ASSERT_FUNC, #x);                 \
        }                                                               \
    } while(0)
#endif

/**
 * Macro which can be used to check the error code. Prints the error code, error location, and the failed statement to
 * serial output.
 * In comparison with AXK_ERROR_CHECK(), this prints the same error message but isn't terminating the program.
 */
#if defined NDEBUG || defined CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT
#define AXK_ERROR_CHECK_WITHOUT_ABORT(x) ({                                         \
        axk_err_t err_rc_ = (x);                                                    \
        err_rc_;                                                                    \
    })
#else
#define AXK_ERROR_CHECK_WITHOUT_ABORT(x) ({                                         \
        axk_err_t err_rc_ = (x);                                                    \
        if (unlikely(err_rc_ != AXK_OK)) {                                          \
            _axk_error_check_failed_without_abort(err_rc_, __FILE__, __LINE__,      \
                                                  __ASSERT_FUNC, #x);               \
        }                                                                           \
        err_rc_;                                                                    \
    })
#endif //NDEBUG

#ifdef __cplusplus
}
#endif
